### ISSUE TITLE
Idea: Scaling (I would like to set it to 0.5)

### ISSUE THREAD

**Issue by mrniddala** [Roundaround/mc-fabric-pickup-notifications#14]

**Comment by Roundaround** [comment]
Yup, already on the TODO list!

Unfortunately though I won't be able to get to it right away. I'm in the middle of completely redoing the internals of the mod in order to stop it from showing notifications when it shouldn't. You'll have to be patient with me :)

**Comment by Roundaround** [comment]
Done a while ago, forgot to close out this issue!
