### ISSUE TITLE
On version 1.3.0 shadows of blocks on notifications is rendering weirdly.

### ISSUE THREAD

**Issue by ViTulyankin** [Roundaround/mc-fabric-pickup-notifications#20]
![2022-09-09_21 34 09](https://user-images.githubusercontent.com/92220631/189399236-3ce80931-e0a6-4806-942e-75bca821c626.png)

On 1.2.4 it is normal

**Comment by Roundaround** [comment]
Nice catch! Fixed in 1.3.1!
