### ISSUE TITLE
beta fabric version

### ISSUE THREAD

**Issue by TI06uK** [Roundaround/mc-fabric-pickup-notifications#6]
This mod is using 0.14.5 fabric loader, which is beta, unstable and incapable with most mods. Why won't you transfer it to a stable 1.13.3?

**Comment by Roundaround** [comment]
Huh, I just went with the version in the Fabric example mod and assumed that was the latest stable version. Where do you see that it's a beta version?

**Comment by TI06uK** [comment]
Discord of fabric

**Comment by Roundaround** [comment]
Lowered the fabric loader version to 0.13.3 in the latest version!

https://modrinth.com/mod/roundaround-pickup-notifications/version/1.1.0
