### ISSUE TITLE
Swapping with offhand causes pickup notification

### ISSUE THREAD

**Issue by Khodyn** [Roundaround/mc-fabric-pickup-notifications#8]
Title is self-explanatory.

**Comment by Roundaround** [comment]
Ah always more edge cases that I have to hard code for. Thanks for reporting, will get to it either tonight or tomorrow

**Comment by Roundaround** [comment]
Turns out this isn't really solvable without having a server-side component. This is fixed now in the latest version (1.1.0) but requires installing the mod on the server for multiplayer.

https://modrinth.com/mod/roundaround-pickup-notifications/version/1.1.0
